from base import *

bobcat = Award( 'Bobcat', (
	("Bobcat Requirement 1", "Learn and say the CUB SCOUT PROMISE and complete the Honesty Character Connection", "1.	Know: Discuss these questions with your family. What is a promise? What does it mean to 'keep your word?' What does honesty mean? What does it mean to 'do your best?'2. Commit: Discuss these questions with your family. Why is a promise important? Why is it important for people to trust you when you give your word? When might it be difficult to keep your word? List examples. 3. Practice: Discuss with family members why it is important to be trustworthy and honest and how can you do your best to be honest when you are doing the activities in Cub Scouting.'I .....(name).... promise to do my best, To do my duty to God and my country, To help other people, and To obey the Law of the Pack.'"),
	("Bobcat Requirement 2", "Say the LAW OF THE PACK.	Tell what it means.", "The Cub Scout follows Akela. The Cub Scout helps the pack go. The pack helps the Cub Scout Grow. The Cub Scout gives goodwill."),
	("Bobcat Requirement 3", "Tell what WEBELOS means", "WE'll BE LOyal Scouts"),
	("Bobcat Requirement 4", "Show the CUB SCOUT SIGN.	Tell what it means.", ""),
	("Bobcat Requirement 5", "Show the CUB SCOUT HANDSHAKE. Tell what it means.", ""),
	("Bobcat Requirement 6", "Say the CUB SCOUT MOTTO. A motto is a guiding principle.", "Do Your Best"),
	("Bobcat Requirement 7", "Give the CUB SCOUT SALUTE.	Tell what it means.", ""),
	("Bobcat Requirement 8", "With your parent or guardian, complete the exercises in the booklet, How to Protect Your Children from Child Abuse.", ""),
	))

wolf = Award( 'Wolf', (
	("Wolf Requirement 1", "Feats of Skill", "", (
		("Wolf Requirement 1a", "Play catch with someone 10 steps away. Play until you can throw and catch.", ""),
		("Wolf Requirement 1b", "Walk a line back and forth. Do it sideways too. Then walk the edge of a board six steps each way.", ""),
		("Wolf Requirement 1c", "Do a front roll.", ""),
		("Wolf Requirement 1d", "Do a back roll. ", ""),
		("Wolf Requirement 1e", "Do a falling forward roll. ", ""),
		("Wolf Requirement 1f", "See how high you can jump. ", ""),
		("Wolf Requirement 1g", "Do the elephant walk, frog leap, and crab walk. ", ""),
		("Wolf Requirement 1h", "Using a basic swim stroke, swim 25 feet. ", ""),
		("Wolf Requirement 1i", "Tread water for 15 seconds or as long as you can. Do your best. ", ""),
		("Wolf Requirement 1j", "Using a basketball or playground ball, do a -", ""),
		("Wolf Requirement 1k", "Do a frog stand. ", ""),
		("Wolf Requirement 1l", "Run or jog in place for 5 minutes.", ""),
	)),
	
	("Wolf Requirement 2", "Your Flag", "", (
		("Wolf Requirement 2a", "Give the Pledge of Allegiance to the flag of the United States of America. Tell what it means. ", ""),
		("Wolf Requirement 2b", "Lead a flag ceremony in your den. ", ""),
		("Wolf Requirement 2c", "Tell how to respect and take care of the U.S. flag. Show three ways to display the flag. ", ""),
		("Wolf Requirement 2d", "Learn about the flag of your state or territory and how to display it. ", ""),
		("Wolf Requirement 2e", "Learn how to raise a U.S. flag properly for an outdoor ceremony ", ""),
		("Wolf Requirement 2f", "Participate in an outdoor flag ceremony. ", ""),
		("Wolf Requirement 2g", "With the help of another person, fold the U.S. flag. ", ""),
	)),

	("Wolf Requirement 3", "Keep Your Body Healthy", "", (
		("Wolf Requirement 3a", "Make a chart and keep track of your health habits for two weeks. ", ""),
		("Wolf Requirement 3b", "Tell four ways to stop the spread of colds. ", ""),
		("Wolf Requirement 3c", "Show what to do for a small cut on your finger. ", ""),
		("Wolf Requirement 3a", "Make a list of phone numbers you need in case of an emergency. Put a copy of this list by each phone or in a central place in your home. Update it often. ", ""),
		("Wolf Requirement 3b", "Tell what to do if someone comes to the door and wants to come in. ", ""),
		("Wolf Requirement 3c", "Tell what to do if someone calls on the phone. ", ""),
		("Wolf Requirement 3d", "When you and your family leave home, ", ""),
		("Wolf Requirement 3e", "Talk with your family members. Agree on the household jobs you will be responsible for. Make a list of your jobs and mark off when you have finished them. Do this for one month. Citizenship Belt Loop #1 ", ""),
		("Wolf Requirement 3f", "Visit an important place in your community, such as a historic or government location. Explain why it is important.", ""),
	)),

	("Wolf Requirement 4", "Know Your Home and Community", "", (
		("Wolf Requirement 4a", "Make a list of phone numbers you need in case of an emergency. Put a copy of this list by each phone or in a central place in your home. Update it often. ", ""),
		("Wolf Requirement 4b", "Tell what to do if someone comes to the door and wants to come in. ", ""),
		("Wolf Requirement 4c", "Tell what to do if someone calls on the phone. ", ""),
		("Wolf Requirement 4d", "When you and your family leave home, ", ""),
		("Wolf Requirement 4e", "Talk with your family members. Agree on the household jobs you will be responsible for. Make a list of your jobs and mark off when you have finished them. Do this for one month.", ""),
		("Wolf Requirement 4f", "Visit an important place in your community, such as a historic or government location. Explain why it is important. ", ""),
	)),

	("Wolf Requirement 5", "Tools for Fixing and Building", "", (
		("Wolf Requirement 5a", "Point out and name seven tools. Do this at home, or go to a hardware store with an adult. Tell what each tool does. ", ""),
		("Wolf Requirement 5b", "Show how to use pliers. ", ""),
		("Wolf Requirement 5c", "Identify a Philips head and a standard screw. Then use the right tool to drive and then remove one from a board. ", ""),
		("Wolf Requirement 5d", "Show how to use a hammer. ", ""),
		("Wolf Requirement 5e", "Make a birdhouse, a set of bookends, or something else useful. ", ""),
	)),

	("Wolf Requirement 6", "Start a Collection", "", (
		("Wolf Requirement 6a", "Complete the Character Connection for Positive Attitude.", "Know. Discuss with your family how a cheerful and positive attitude will help you do your best at school and in other areas of your life. Commit. Discuss with your family how gathering items for a collection may be difficult. How does a hopeful and cheerful attitude help you to keep looking for more items. Why is a positive attitude important?Practice. Practice having a positive attitude while doing the requirements for 'Start a Collection.' "),
		("Wolf Requirement 6b", "Make a collection of anything you like. Start with 10 things. Put them together in a neat way. ", ""),
		("Wolf Requirement 6c", "Show and explain your collection to another person.", ""),
	)),

	("Wolf Requirement 7", "Your Living World", "", (
		("Wolf Requirement 7a", "Complete the Character Connection for Respect.", "Know. Discuss these questions with your family: What things have people done to show a lack of respect to our world? Why is it important to respect our environment and ntural resources? How can you show respect for your environment? Commit. Discuss with your family how you feel when you see places in your neighborhood that have lots of litter. Name one thing you can do to help the environment. Practice. Practice being respectful while doing the requirements for 'Your Living World.' "),
		("Wolf Requirement 7b", "Land, air and water can get dirty. Discuss with your family ways this can happen. ", ""),
		("Wolf Requirement 7c", "It takes a lot of energy to make glass, cans, and paper products. You can help save energy by collecting these items for use again. Find out how recycling is done where you live. Find out what items you can recycle. ", ""),
		("Wolf Requirement 7d", "With an adult, pick up litter in your neighborhood. Wear gloves to protect your hands against germs and cuts from sharp objects. ", ""),
		("Wolf Requirement 7e", "With an adult, find three stories that tell how people are protecting our world. Read and discuss them together. ", ""),
		("Wolf Requirement 7f", "Besides recycling, there are other ways to save energy. List three ways you can save energy, and do them.", ""),
	)),
	
	("Wolf Requirement 8", "Cooking and Eating", "", (
		("Wolf Requirement 8a", "Study the Food Guide Pyramid. Name some foods from each of the food groups shown in the pyramid. ", ""),
		("Wolf Requirement 8b", "Plan the meals you and your family should have for one day. List things your family should have from the food groups shown in the Food Group Pyramid. At each meal, you should have foods from at least three food groups. ", ""),
		("Wolf Requirement 8c", "Help fix at least one meal for your family. Help set the table, cook the food, and wash the dishes. ", ""),
		("Wolf Requirement 8d", "Fix your own breakfast. Wash and put away the dishes. ", ""),
		("Wolf Requirement 8e", "With an adult, help to plan, prepare, and cook an outdoor meal.", ""),
	)),

	("Wolf Requirement 9", "Be Safe at Home and on the Street", "", (
		("Wolf Requirement 9a", "Complete the Character Connection for Responsibility.", " Know. Discuss these questions with your family: How does being responsible help us be safe? Within the past week, how did you show responsibility? Commit. Discuss these questions with your family: What happens when people are not responsible? What things can make you forget to be responsible? What things will help you be more responsible? Practice. Practice being responsible while doing the requirements for 'Be Safe at Home and on the Street.' "),
		("Wolf Requirement 9b", "WITH AN ADULT, check your home for hazards and know how to make your home safe. Citizenship Pin #4 ", ""),
		("Wolf Requirement 9c", "WITH AN ADULT, check your home for danger from fire.", ""),
		("Wolf Requirement 9d", "Practice good rules of street and road safety. ", ""),
		("Wolf Requirement 9e", "Know the rules of bike safety. ", ""),
	)), 

	("Wolf Requirement 10", "Family Fun", "", (
		("Wolf Requirement 10a", "Complete the Character Connection for Cooperation.", " Know. Discuss these questions with your family: What is 'cooperation'? Why do people need to cooperate when they are doing things together? Name some ways that you can be helpful and cooperate with others. Commit. Discuss with your family what makes it hard to cooperate. How do listening, sharing, and persuading help us cooperate? Practice. Practice being cooperative while doing the requirements for 'Family Fun.' "),
		("Wolf Requirement 10b", "Make a game like one of these. Play it with your family. ", ""),
		("Wolf Requirement 10c", "Plan a walk. Go to a park or a wooded area, or visit a zoo or museum with your family. ", ""),
		("Wolf Requirement 10d", "Read a book or Boys' Life magazine with your family. Take turns reading aloud. Communicating Pin #5 ", ""),
		("Wolf Requirement 10e", "Decide with Akela. what you will watch on television or listen to on the radio. ", ""),
		("Wolf Requirement 10f", "Attend a concert, a play, or other live program with your family.", ""),
		("Wolf Requirement 10g", "Have a family Board Game night at home with members of your family.", ""),
	)),

	("Wolf Requirement 11", "Duty to God", "", (
		("Wolf Requirement 11a", "Complete the Character Connection for Faith.", "Know. What is 'faith'? With your family, discuss some people who have shown their faith - who have shown an inner strength based on their trust in a higher power or cause. Discuss the good qualities of these people. Commit. Discuss these questions with your family: What problems did these faithful people overcome to follow or practice their beliefs? What challenges might you face in doing your duty to God? Who can help you with these challenges? Practice. Practice your faith while doing the requirements for 'Duty to God.' "),
		("Wolf Requirement 11b", "Talk with your family about what they believe is their duty to God. ", ""),
		("Wolf Requirement 11c", "Give two ideas on how you can practice or demonstrate your religious beliefs. Choose one and do it. ", ""),
		("Wolf Requirement 11d", "Find out how you can help your church, synagogue, mosque, temple, or religious fellowship. ", ""),
	)), 

	("Wolf Requirement 12", "Making Choices", "", (
		("Wolf Requirement 12a", "Complete the Character Connection for Courage.Know. Discuss with your family what 'courage' is. Review the requirements and discuss how you might need courage in each one to do what is right. Commit. Give some examples of when it is hard to do the right thing. Discuss with your family times that it might take courage to be honest and kind. Tell about a time in your life when you needed to be brave and courageous to do the right thing. Practice. Practice learning about courage while doing the requirements for 'Making Choices.' With family members, act out the choices you would make for some of the requirements. ", ""),
		("Wolf Requirement 12b", "There is an older boy who hangs around Jason's school. He tries to give drugs to the children. What would you do if you were Jason? ", ""),
		("Wolf Requirement 12c", "Lee is home alone. The phone rings. When Lee answers, a stranger asks if Lee's mother is home. She is not. Lee is alone. What would you do if you were Lee? ", ""),
		("Wolf Requirement 12d", "Justin is new to your school. He has braces on his legs and walks with a limp. Some of the kids at school tease him. They want you to tease him, too. What would you do? ", ""),
		("Wolf Requirement 12e", "Juan is on a walk with his little sister. A car stops and a man asks them to come over to the car. What would you do if you were Juan? ", ""),
		("Wolf Requirement 12f", "Matthew's grandmother gives him money to buy an ice-cream cone. On the way to the store, a bigger boy asks for money and threatens to hit Matthew if he does not give him some money. If you were Matthew what would you do? ", ""),
		("Wolf Requirement 12g", "Chris and his little brother are home alone in the afternoon. A woman knocks on the door and says she wants to read the meter. She is not wearing a uniform. What would you do if you were Chris? ", ""),
		("Wolf Requirement 12h", "Sam is home alone. He looks out the window and sees a man trying to break into a neighbor's back door. What would you do if you were Sam? ", ""),
		("Wolf Requirement 12i", "Mr. Palmer is blind. He has a guide dog. One day as he is crossing the street, some kids whistle and call to the dog. They want you and your friends to call the dog, too. What would you do? ", ""),
		("Wolf Requirement 12j", "Some kids who go to Bob's school want him to steal candy and gum from a store, which they can share later. Bob knows this is wrong, but he wants to be popular with these kids. What would you do if you were Bob? ", ""),
		("Wolf Requirement 12k", "Paul and his little sister are playing outdoors. A very friendly, elderly woman stops and watches the children for a while. Paul doesn't know the woman. She starts to talk to them and offers to take Paul's little sister on a walk around the block. What would you do? ", ""),
	))
	))

wolf_gold_arrow_point = Award( 'Wolf Gold Arrow Point', (
	("Wolf Elective 1", " It's a Secret", ""),
	("Wolf Elective 1d", "Use 12 American Indian signs to tell a story.", ""),
	("Wolf Elective 1b", "Write to a friend in invisible 'ink'.", ""),
	("Wolf Elective 1c", "'Write' your name using American Sign Language. People who are deaf use this language.", ""),
	("Wolf Elective 1a", "Use a secret code.", ""),
	("Wolf Elective 2", " Be an Actor", ""),
	("Wolf Elective 2e", "Make a paper-sack mask for a skit.", ""),
	("Wolf Elective 2c", "Make sound effects for a skit.", ""),
	("Wolf Elective 2d", "Be the announcer for a skit.", ""),
	("Wolf Elective 2b", "Make some scenery for a skit.", ""),
	("Wolf Elective 2a", "Help to plan and put on a skit with costumes.", ""),
	("Wolf Elective 3", " Make It Yourself", ""),
	("Wolf Elective 3e", "Or make something else.", ""),
	("Wolf Elective 3d", "Make a door stop.", ""),
	("Wolf Elective 3c", "Make and use a bench fork.", ""),
	("Wolf Elective 3b", "Use the ruler on this page to see how far you can stretch your hand.", ""),
	("Wolf Elective 3a", "Make something useful for your home or school. Start with a recipe card holder.", ""),
	("Wolf Elective 4", " Play a Game", ""),
	("Wolf Elective 4f", "Play a wide-area or large group game with your den or pack.", ""),
	("Wolf Elective 4e", "Play a game of marbles.", ""),
	("Wolf Elective 4c", "Play Ring Toss.", ""),
	("Wolf Elective 4d", "Play Beanbag Toss.", ""),
	("Wolf Elective 4b", "Play Marble Sharpshooter.", ""),
	("Wolf Elective 4a", "Play Pie-tin Washer Toss.", ""),
	("Wolf Elective 5", " Spare-Time Fun", ""),
	("Wolf Elective 5h", "Make or put together some kind of model boat, airplane, train, or car.", ""),
	("Wolf Elective 5i", "Make or put together some kind of model boat, airplane, train, or car.", ""),
	("Wolf Elective 5g", "Make or put together some kind of model boat, airplane, train, or car.", ""),
	("Wolf Elective 5f", "Make a model boat with a rubber-band propeller.", ""),
	("Wolf Elective 5e", "Make and use a reel for kite string.", ""),
	("Wolf Elective 5d", "Make and fly a three-stick kite.", ""),
	("Wolf Elective 5b", "Make and fly a paper bag kite.", ""),
	("Wolf Elective 5c", "Make and fly a two-stick kite.", ""),
	("Wolf Elective 5a", "Explain safety rules for kite flying.", ""),
	("Wolf Elective 6", " Books, Books, Books", ""),
	("Wolf Elective 6c", "Books are important. Show that you know how to take care of them. Open a new book the right way. Make a paper or plastic cover for it or another book.", ""),
	("Wolf Elective 6b", "Choose a book on a subject you like and read it. With an adult, discuss what you read and what you think about it.", ""),
	("Wolf Elective 6a", "Visit a bookstore or go to a public library with an adult. Find out how to get your own library card. Name four kinds of books that interest you (for example, history, science fiction, how-to-books).", ""),
	("Wolf Elective 7", " Foot Power", ""),
	("Wolf Elective 7c", "Make a pair of 'foot racers' and use them with a friend.", ""),
	("Wolf Elective 7b", "Make a pair of 'puddle jumpers' and walk with them.", ""),
	("Wolf Elective 7a", "Learn to walk on a pair of stilts.", ""),
	("Wolf Elective 8", " Machine Power", ""),
	("Wolf Elective 8c", "Show how to use a pulley.", ""),
	("Wolf Elective 8d", "Make and use a windlass.", ""),
	("Wolf Elective 8b", "Help an adult do a job using a wheel and axle.", ""),
	("Wolf Elective 8a", "Name 10 kinds of trucks, construction machinery, or farm machinery and tell what each is used for.", ""),
	("Wolf Elective 9", " Let's Have a Party", ""),
	("Wolf Elective 9b", " c. Make a gift or toy like one of these and give it to someone.", ""),
	("Wolf Elective 9a", "Help with a home or den party.", ""),
	("Wolf Elective 10", " American Indian Lore", ""),
	("Wolf Elective 10a", "Read a book or tell a story about American Indians, past or present.", ""),
	("Wolf Elective 10b", "Make a musical instrument American Indians used.", ""),
	("Wolf Elective 10c", "Make traditional American Indian clothing.", ""),
	("Wolf Elective 10d", "Make a traditional item or instrument that American Indians used to make their lives easier.", ""),
	("Wolf Elective 10e", "Make a model of a traditional American Indian house.", ""),
	("Wolf Elective 10f", "Learn 12 American Indian word pictures and write a story with them.", ""),
	("Wolf Elective 11", " Sing-Along", ""),
	("Wolf Elective 11f", "Sing a song with your den at a pack meeting.", ""),
	("Wolf Elective 11e", "Learn and sing a song that would be sung as a grace before meals. Write the words in the space below.", ""),
	("Wolf Elective 11d", "Learn the words and sing the first verse of three other songs, hymns, or prayers. Write the verse of one of the songs you learned in the space below.", ""),
	("Wolf Elective 11c", "Learn the words and sing three Cub Scouting songs.", ""),
	("Wolf Elective 11a", "Learn and sing the first and last verses of 'America.'", ""),
	("Wolf Elective 11b", "Learn and sing the first verse of our national anthem.", ""),
	("Wolf Elective 12", " Be an Artist", ""),
	("Wolf Elective 12f", "Make a poster for a Cub Scout project or a pack meeting", ""),
	("Wolf Elective 12e", "Make a stencil pattern.", ""),
	("Wolf Elective 12d", "Help draw, paint, or color some scenery for a skit, play, or puppet show.", ""),
	("Wolf Elective 12c", "Mix yellow and blue paints, mix yellow and red, and mix red and blue. Tell what color you get from each mixture.", ""),
	("Wolf Elective 12b", "Tell a story in three steps by drawing three cartoons.", ""),
	("Wolf Elective 12a", "Make a freehand sketch of a person, place, or thing.", ""),
	("Wolf Elective 13", " Birds", ""),
	("Wolf Elective 13f", "Put out a birdhouse and tell which birds use it.", ""),
	("Wolf Elective 13e", "Feed wild birds and tell which birds you fed.", ""),
	("Wolf Elective 13d", "Point out 10 different kinds of birds (five may be from pictures).", ""),
	("Wolf Elective 13c", "Read a book about birds.", ""),
	("Wolf Elective 13b", "Put out nesting material (short pieces of yarn and string) for birds and tell which birds might use it.", ""),
	("Wolf Elective 13a", "Make a list of all the birds you saw in a week and tell where you saw them (field, forest, marsh, yard, or park).", ""),
	("Wolf Elective 13T", "s elective is also part of the Cub Scout World Conservation Award.", ""),
	("Wolf Elective 14", " Pets", ""),
	("Wolf Elective 14d", "Tell what is meant by rabid. Name some animals that can have rabies. Tell what you should do if you see a dog or wild animal that is behaving strangely. Tell what you should do if you find a dead animal.", ""),
	("Wolf Elective 14c", "Read a book about a pet and tell about it at a den meeting.", ""),
	("Wolf Elective 14b", "Know what to do when you meet a strange dog.", ""),
	("Wolf Elective 14a", "Take care of a pet.", ""),
	("Wolf Elective 15", " Grow Something", ""),
	("Wolf Elective 15e", "Visit a botanical garden or other agricultural exhibition in your area.", ""),
	("Wolf Elective 15c", "Grow a plant indoors.", ""),
	("Wolf Elective 15d", "Plant and raise vegetables.", ""),
	("Wolf Elective 15b", "Plant and raise a flower bed.", ""),
	("Wolf Elective 15a", "Plant and raise a box garden.", ""),
	("Wolf Elective 16", " Family Alert", ""),
	("Wolf Elective 16c", "Make a list of your first-aid supplies, or make a first-aid kit. Know where the first-aid things are kept.", ""),
	("Wolf Elective 16a", "Talk with your family about what you will do in an emergency.", ""),
	("Wolf Elective 16b", "In case of a bad storm or flood, know where you can get safe food and water in your home. Tell how to purify water. Show one way. Know where and how to shut off water, electricity, gas, or oil.", ""),
	("Wolf Elective 17", " Tie It Right", ""),
	("Wolf Elective 17f", "Learn to tie a necktie.", ""),
	("Wolf Elective 17g", "Wrap the end of a rope with tape to keep it from unwinding.", ""),
	("Wolf Elective 17e", "Tie two cords together with an overhand knot.", ""),
	("Wolf Elective 17d", "Tie a stack of newspapers the right way.", ""),
	("Wolf Elective 17c", "Wrap and tie a package so that it is neat and tight.", ""),
	("Wolf Elective 17b", "Tie your shoelaces with a square bow knot.", ""),
	("Wolf Elective 17a", "Learn to tie an overhand knot and a square knot.", ""),
	("Wolf Elective 18", " Outdoor Adventure", ""),
	("Wolf Elective 18g", "Point out poisonous plants. Tell what to do if you accidentally touch one of them.", ""),
	("Wolf Elective 18e", "Help plan and lay out an adventure trail.", ""),
	("Wolf Elective 18f", "Take part in two summertime pack events with your den.", ""),
	("Wolf Elective 18d", "Help plan and lay out an obstacle race. Use this idea or make up your own.", ""),
	("Wolf Elective 18c", "Help plan and lay out a treasure hunt something like this.", ""),
	("Wolf Elective 18b", "With an adult, help plan and run a family or den outing.", ""),
	("Wolf Elective 18a", "Help plan and hold a picnic with your family or den.", ""),
	("Wolf Elective 19", " Fishing", ""),
	("Wolf Elective 19f", "Show how to use a rod and reel.", ""),
	("Wolf Elective 19e", "Tell about some of the fishing laws where you live.", ""),
	("Wolf Elective 19d", "Know the rules of safe fishing.", ""),
	("Wolf Elective 19c", "Fish with members of your family or an adult. Bait your hook and do your best to catch a fish.", ""),
	("Wolf Elective 19b", "Rig a pole with the right kind of line and hook. Attach a bobber and sinker, if you need them. Then go fishing.", ""),
	("Wolf Elective 19a", "Identify five different kinds of fish.", ""),
	("Wolf Elective 20", " Sports", ""),
	("Wolf Elective 20d", "Understand the safety and courtesy code for skiing. Show walking and the kick turn. Do climbing with a side step or herringbone. Show the snowplow or stem turn, and how to get up from a fall.", ""),
	("Wolf Elective 20c", "Earn the Cub Scouting shooting sports Archery belt loop.", ""),
	("Wolf Elective 20b", "Know boating safety rules.", ""),
	("Wolf Elective 20a", "Play a game of tennis, table tennis, or badminton.", ""),
	("Wolf Elective 20e", "Know the safety rules for ice skating. Skate, without falling, as far as you can walk in 50 steps. Come to a stop. Turn from forward to backward.", ""),
	("Wolf Elective 20f", "In roller skating, know the safety rules. From a standing start, skate forward as far as you can walk in 50 steps. Come to a stop within 10 walking steps. Skate around a corner one way without coasting. Then do the same coming back. Turn from forward to backward.", ""),
	("Wolf Elective 20g", "Go bowling.", ""),
	("Wolf Elective 20h", "Show how to make a sprint start in track. See how far you can run in 10 seconds.", ""),
	("Wolf Elective 20i", "Do a standing long jump. Jump as far as you can.", ""),
	("Wolf Elective 20j", "Play a game of flag football.", ""),
	("Wolf Elective 20k", "Show how to dribble and kick a soccer ball. Take part in a game.", ""),
	("Wolf Elective 20l", "Play a game of baseball or softball.", ""),
	("Wolf Elective 20m", "Show how to shoot, pass, and dribble a basketball. Take part in a game.", ""),
	("Wolf Elective 20n", "Earn the Cub Scouting shooting sports BB-gun shooting belt loop.", ""),
	("Wolf Elective 20o", "With your den, participate in four outdoor physical fitness-related activities.", ""),
	("Wolf Elective 21", " Computers", ""),
	("Wolf Elective 21c", "Tell what a computer mouse is. Describe how a CD-ROM is used.", ""),
	("Wolf Elective 21b", "Explain what a computer program does. Use a program to write a report for school, to write a letter, or for something.", ""),
	("Wolf Elective 21a", "Visit a business where computers are used. Find out what the computers do.", ""),
	("Wolf Elective 22", " Say It Right", ""),
	("Wolf Elective 22e", "Invite a boy to join Cub Scouting or help a new Cub Scout through the Bobcat trail.", ""),
	("Wolf Elective 22d", "Tell how to get to a nearby fire station or police station from your home, your den meeting place, and school. Use directions and street names.", ""),
	("Wolf Elective 22c", "Tell a short story to your den, your den leader, or an adult.", ""),
	("Wolf Elective 22a", "Say 'hello' in a language other than English.", ""),
	("Wolf Elective 22b", "Count to 10 in a language other than English.", ""),
	("Wolf Elective 23", " Let's Go Camping", ""),
	("Wolf Elective 23h", "With your den or pack or family, participate in a worship service outdoors.", ""),
	("Wolf Elective 23g", "Participate with your den at a campfire in front of your pack.", ""),
	("Wolf Elective 23f", "Attend resident camp in your area.", ""),
	("Wolf Elective 23e", "Attend day camp in your area.", ""),
	("Wolf Elective 23d", "Explain Buddy System.", ""),
	("Wolf Elective 23c", "Tell what to do if you get lost.", ""),
	("Wolf Elective 23b", "Explain the basics of how to take care of yourself in the outdoors.", ""),
	("Wolf Elective 23a", "Participate with your pack on an overnight campout.", ""),
	))

art_belt_loop = Award( 'Art Belt Loop', (
	("Art Belt Loop Requirement 1", "Make a list of common materials used to create visual art compositions", ""),
	("Art Belt Loop Requirement 2", "Demonstrate how six of the following elements of design are used in a drawing: lines, circles, dots, shapes, colors, patterns, textures, space, balance, or perspective.", ""),
	("Art Belt Loop Requirement 2", "Identify the three primary colors and the three secondary colors that can be made by mixing them. Show how this is done using paints or markers. Use the primary and secondary colors to create a painting."),
 ))
